---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.APP_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{.APP_NAME}}
    spec:
      containers:
      - name: hello-world-nodejs
        image: quay.io/ukhomeofficedigital/dsp-hello-world:{{.APP_VERSION}}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
        env:
          - name: MYSUPERSECRET
            valueFrom:
              secretKeyRef:
                name: {{.APP_NAME}}
                key: supersecret
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.6.1
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '4000'
          - name: LOG_FORMAT_NAME
            value: json
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 443
